# Generated by Django 4.1.7 on 2023-06-14 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_active_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at',), 'permissions': []},
        ),
    ]
