# Generated by Django 4.1.7 on 2023-06-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='issuedBy',
            field=models.UUIDField(verbose_name='Issued By'),
        ),
    ]
