# Generated by Django 4.1.7 on 2023-06-20 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abattoirs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=200, verbose_name='Certificate code')),
                ('issuedBy', models.UUIDField(verbose_name='Issues By')),
                ('beefWeightInKg', models.DecimalField(decimal_places=3, max_digits=4)),
                ('animalSpecie', models.CharField(max_length=200, verbose_name='Animal Specie')),
                ('typeOfParts', models.CharField(max_length=200, verbose_name='Types Of Part')),
                ('typeOfPackaging', models.CharField(max_length=200, verbose_name='Types Of Packaging')),
                ('numberOfParts', models.IntegerField(verbose_name='Number Of Parts')),
                ('identificationMark', models.CharField(max_length=200)),
                ('serialNumberOfCarcass', models.CharField(max_length=200)),
                ('dispatchedTo', models.CharField(max_length=200)),
                ('abattoir', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='abattoir', to='abattoirs.abattoir')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
            },
        ),
    ]
