# Generated by Django 4.1.7 on 2023-06-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abattoir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operatingAddress', models.CharField(max_length=200, verbose_name='Operating Address')),
                ('contactPhone', models.CharField(max_length=200, verbose_name='Contact Phonenumber')),
                ('emailAddress', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('name', models.CharField(max_length=200, verbose_name='Abattoir Name')),
                ('accountNumber', models.CharField(max_length=200, verbose_name='Account Number')),
                ('bankCode', models.CharField(max_length=200, verbose_name='Bank Code')),
                ('bankName', models.CharField(max_length=200, verbose_name='Bank Name')),
                ('accountName', models.CharField(max_length=200, verbose_name='Account Name')),
                ('approvalNumber', models.CharField(max_length=200, verbose_name='Approval Number')),
                ('country', models.CharField(max_length=200, verbose_name='Country')),
                ('state', models.CharField(max_length=200, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Abattoir',
                'verbose_name_plural': 'Abattoirs',
            },
        ),
    ]
